language: objective-c
script: xcodebuild -workspace inkcluded-405.xcworkspace -scheme inkcluded-405 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
notifications:
  slack: boba-slo:yOTZTRMNoMyYIWGhpDX7xqLl
osx_image: xcode8.2
