# .slather.yml

xcodeproj: inkcluded-405.xcodeproj/
xcworkspace: inkcluded-405.xcworkspace
scheme: inkcluded-405
ignore:
  - ../*
  - Frameworks/*

# 

slather coverage --scheme inkcluded-405 --show --ignore '../*' --ignore 'Frameworks/*' --ignore 'inkcluded-405/GroupsTableViewCell.swift' --ignore 'inkcluded-405/FriendTableViewCell.swift' --ignore 'inkcluded-405/MessageTableViewCell.swift' --ignore 'inkcluded-405/CanvasMenuView.swift' --ignore 'inkcluded-405/DrawView.swift' --ignore 'inkcluded-405/DraggableImageView.swift' --ignore 'inkcluded-405/DraggableTextView.swift' --ignore 'inkcluded-405/LoadView.swift' --html --workspace inkcluded-405.xcworkspace inkcluded-405.xcodeproj/
